### ISSUE TITLE
the python file will result in an error!

### ISSUE THREAD

**Issue by MadhanDevlpr** [ps345/test-repo-ps#3]
Atleast add a valid code for contributing

**Comment by MadhanDevlpr** [comment]
Or this repo might be going into the excluded list in hacktoberfest

**Comment by ps345** [comment]
ohh are the checking code as well ?

**Comment by MadhanDevlpr** [comment]
Yeah

**Comment by ps345** [comment]
ok then let me add some random functions

**Comment by MadhanDevlpr** [comment]
Make a contribute-able project for the public and not just for you

**Comment by ps345** [comment]
Your contact number please
